# /home/user/.config/tmuxinator/baseline.yml
#!WARNING: this script will not work directly without configured ssh ids - remove ssh commands to run on single node, and update config param on each node to be different files with different private keys

name: async
root: /Users/shash/Downloads/FL/UnifyFL

windows:
  - aggregators:
      layout: tiled
      panes:
        - aggregator:
            - cd /Users/shash/Downloads/FL/UnifyFL
            - .venv312/bin/python -m unifyfl.async.async configs/async/agg.config.json
       
  - scorers:
      layout: tiled
      panes:
        - scorer:
            - cd /Users/shash/Downloads/FL/UnifyFL
            - .venv312/bin/python -m unifyfl.async.scorer configs/async/agg.config.json

  - clients:
      layout: tiled
      panes:
        - clients_docker:
            - cd /Users/shash/Downloads/FL/UnifyFL
            - docker compose up

  - support:
      layout: tiled
      panes:
        - ipfs:
            - ipfs daemon